blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(),
        name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

]

bookmark/urls.py
from django.conf.urls import url
from bookmark.views import *

urlpatterns =[
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail')
]

photo/urls.py
from django.conf.urls import url
from photo.views import *

urlpatterns = [
    # --- Example : /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # --- Example : /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # --- Example : /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # --- Example : /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
]

practice3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from home.views import HomeView
from home.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
                  url(r'^admin/', admin.site.urls),

                  url(r'^account/', include('django.contrib.auth.urls')),
                  url(r'^account/register/$', UserCreateView.as_view(), name='register'),
                  url(r'^account/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

                  url(r'^$', HomeView.as_view(), name='home'),
                  url(r'bookmark/', include('bookmark.urls', namespace='bookmark')),
                  url(r'^blog/', include('blog.urls', namespace='blog')),
                  url(r'^photo/', include('photo.urls', namespace='photo')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse

from tagging.fields import TagField


# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True,
                            help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100,
                                   blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    tag = TagField();

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

bookmark/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

from django.core.urlresolvers import reverse

from photo.fields import ThumbnailImageField

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

blog/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from blog.models import Post


# Create your views here.

# --- TemplateView
class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'


# --- ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 3


# --- TaggedObjectList
class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'


# --- DetailView
class PostDV(DetailView):
    model = Post


# --- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark


# Create your views here.

# --- ListView
class BookmarkLV(ListView):
    model = Bookmark


# --- DetailView
class BookmarkDV(DetailView):
    model = Bookmark

home/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy


# Create your views here.

class HomeView(TemplateView):
    template_name = 'home.html'


# --- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

photo/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from photo.models import Album, Photo


# Create your views here.

class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"

    <title>{% block title %}Django Web Programming{% endblock %}</title>
</head>
<body>

<div id = "header">
    {% if user.is_active %}
         <h4>Welcome,
             <strong>{% firstof user.get_short_name user.get_username %}</strong>
        <a href="{% url 'password_change' %}">Change Password</a>
        <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4>Welcome, Visitor /
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'photo:index' %}">Photo</a></li>

    <li><a href="#">Add&bigtriangledown;</a>
        <ul>
            <li><a href="#">Bookmark</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Photo</a></li>
        </ul>
    </li>
    <li><a href="#">Change&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="{% url 'photo:index' %}">Photo</a></li>
        </ul>
    </li>

    <li><a href="#">Archive</a></li>
    <li><a href="#">Search</a></li>
    <li><a href="#">Photo</a></li>

</div>

{% block content %}{% endblock %}
{% block footer %}{% endblock %}

</body>
</html>

templates/blog/post_all.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->


    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">


    <title>BLOG</title>
</head>
<body>
<div class="container">
    <h1 class="center-block" style="width:300px;padding:15px;">Game List</h1>
    {% for post in posts %}
        <h2 class="center-block" style="width:300px;padding:15px;">
            <a href='{{ post.get_absolute_url }}' >
                {{ post.title }}</a>
        </h2>
        <p class="center-block" style="width:300px;padding:15px;">{{ post.modify_date|date:"N d, Y" }}
        <br/>
        {{ post.description }}
        </p>
    {% endfor %}
    <br/>

    <div>
    <span class="center-block" style="width:300px;padding:15px;">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/blog/post_archive.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->


    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">


    <title>BLOG</title>
</head>
<body>
    <h1>Post Archives until {% now "N d, Y" %}</h1>

    <ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
            Year-{{ date|date:"Y" }}
        </a>
    </li>
    {% endfor %}

    </ul>

    <br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y -m -d" }}&nbsp;&nbsp;&nbsp;</li>
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        {% endfor %}
    </ul>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/blog/post_archive_day.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->


    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">


    <title>BLOG</title>
</head>
<body>
<h1>Post Archive for {{ day|day:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
            <li>
            {{ post.modify_date|date:"Y -m -d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/blog/post_archive_month.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->


    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">


    <title>BLOG</title>
</head>
<body>
    <h1>Post Archive for {{ month|date:"N, Y" }}</h1>

    <div>
        <ul>
            {%  for post in object_list %}
            <li>
            {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/blog/post_archive_year.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->


    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">


    <title>BLOG</title>
</head>
<body>

<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in data_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">
                {{ date|date:"F" }}
            </a>
        </li>
    {% endfor %}
</ul>

<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y -m -d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}">
            <strong>{{ post.title }}</strong>
        </a>
        </li>
        {% endfor %}
    </ul>

</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
    <title>HRTF LAB</title>


    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">


    <title>Bookmark</title>
</head>
<body>

    <div id="content">
        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
                <li><a href="{% url 'bookmark:detail' bookmark.id %}">
                <h3> {{ bookmark|default:"nothing"}}</h3>
                </a></li>
            {% endfor %}
        </ul>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>


</body>
</html>

templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h2>{{ object.name }}</h2>
        &emsp;<b><i>{{ object.description }}</i></b>
        <hr/>
        <div class="album-detail">
            {% for photo in object.photo_set.all %}
                <div class="album-detail-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumbnail" src="{{ photo.imgae.thumb_url }}"/>
                    </a>
                    <li>{{ photo.title }}</li>
                    <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "photo/photo.css" %} {% endblock %}

{% block content %}
    {% for item in object_list %}
        <div class="clear_float">
            <h2 style="dispaly:inline"><a href="{% url 'photo:album_detail' item.id %}">
                {{ item.name }}</a></h2>
            &emsp;<b><i>{{ item.description }}</i></b>
        </div>

        <hr/>

        <div class="album-list">
            {% for photo in item.photo_set.all|slice:":5" %}
                <div class="album-list-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumnail" src="{{ photo.image.thumb_url }}"/>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

templates/tagging/tagging_cloud.html
{% extends "base.html" %}

{% block title %}tagging_cloud.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Blog Tag Cloud</h1>
        <div class="tag-cloud">
            {% load tagging_tags %}
            {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
            {% for tag in tags %}
                <span class="tag-{{ tags.font_size }}">
            <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}({{ tag.font_size }})</a>
        </span>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/tagging/tagging_post_list.html
{% extends "base.html" %}

{% block title %}tagging_post_list.html{% endblock %}

{% block content %}
<div id="content">
<h1>Posts for tag - {{ tag.name }}</h1>
{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}
</div>
{% endblock %}